# Generated by Django 4.1 on 2022-09-03 13:27

# noinspection PyUnresolvedReferences
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumClient', models.CharField(max_length=200, null=True)),
                ('NomClient', models.CharField(max_length=200, null=True)),
                ('AdrClient', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
