version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://william:cummial@db:5432/gestion_voiture
      - POSTGRES_DB=gestion_voiture
      - POSTGRES_USER=william
      - POSTGRES_PASSWORD=cummial
    depends_on:
      db:
        condition: service_healthy  # Ajouté
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media 

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gestion_voiture
      - POSTGRES_USER=william
      - POSTGRES_PASSWORD=cummial
    ports:
      - "5432:5432"
    healthcheck:       # Ajouté
      test: ["CMD-SHELL", "pg_isready -U william -d gestion_voiture"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:
  media_volume: