services:
  - type: web
    name: gestion-voiture
    env: docker
    region: frankfurt  # ou une autre région proche
    plan: free
    branch: main  # ou votre branche principale
    dockerfilePath: ./Dockerfile
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: DATABASE_URL
        fromDatabase:
          name: gestion_voiture
          property: connectionString

databases:
  - name: gestion_voiture
    plan: free