# Generated by Django 4.2.4 on 2023-08-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='StockActuel',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='StockInit',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='id',
        ),
        migrations.AddField(
            model_name='voiture',
            name='Matricule',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
    ]
