# Generated by Django 4.2.4 on 2023-08-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0002_remove_voiture_stockactuel_remove_voiture_stockinit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='voiture_images/'),
        ),
    ]
