# Generated by Django 4.1 on 2022-09-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('voiture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantite', models.FloatField(null=True)),
                ('DateVente', models.DateTimeField(auto_now_add=True, null=True)),
                ('Marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voiture.voiture')),
                ('NumCompte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
            ],
        ),
    ]
