# Generated by Django 4.1 on 2022-09-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vente',
            old_name='NumCompte',
            new_name='NomClient',
        ),
    ]
