# Generated by Django 4.2.4 on 2023-08-15 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0002_remove_voiture_stockactuel_remove_voiture_stockinit_and_more'),
        ('client', '0002_remove_client_id_alter_client_adrclient_and_more'),
        ('vente', '0002_rename_numcompte_vente_nomclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='Marque',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='NomClient',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='Quantite',
        ),
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='vente',
            name='voiture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voiture.voiture'),
        ),
    ]
