# Generated by Django 4.2.4 on 2023-08-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0003_remove_vente_marque_remove_vente_nomclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
